"""

Revision ID: 460e17ebd6ac
Revises: b26613b07c64
Create Date: 2025-05-29 15:55:51.724166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '460e17ebd6ac'
down_revision: Union[str, None] = 'b26613b07c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_expires_at'), 'otp', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_user_id'), 'otp', ['user_id'], unique=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_otp_user_id'), table_name='otp')
    op.drop_index(op.f('ix_otp_expires_at'), table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###
